<?php 

echo "<h1>Zona privada</h1>";

echo "<ul id='privatezone'>";
  echo "<li><a href='/admin/users/list/'>Gestión de usuarios</a></li>";
  echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
echo "<li><a href='/admin/categoria/list/'>Gestión de categoria</a></li>";
//#NO-BORRAR#//
echo "</ul>";

?>